In [1]:
import pandas as pd

In [2]:
df_complete_186_files = pd.read_csv("/Users/mak/Desktop/Python challenge/df_complete_186_files.csv")

In [4]:
columnas_datetime = ["operating_date", "closing_time", "captured_time"]

In [6]:
for column in columnas_datetime:
    if column in df_complete_186_files.columns:
        df_complete_186_files[column] = pd.to_datetime(df_complete_186_files[column], errors='coerce')

In [7]:
df_complete_186_files.dtypes

sucursal                               str
operating_date              datetime64[us]
day_name                               str
closing_time                datetime64[us]
captured_time               datetime64[us]
week_number                          int64
pdv_txn_id                           int64
order_id                             int64
order_type                             str
order_subtype                          str
table_number                         int64
party_size                           int64
server                                 str
terminal                               str
capture_terminal                       str
action                                 str
item                                   str
modifier                               str
group_type                             str
group                                  str
description                            str
is_modifier                           bool
quantity                           float64
unit_price                         float64
unit_price_with_mods               float64
cost_actual                        float64
cost_with_mods                     float64
cost_ideal                         float64
discount                           float64
subtotal_ticket                    float64
iva_ticket                         float64
ieps_ticket                        float64
total_ticket                       float64
subtotal_item                      float64
iva_item                           float64
ieps_item                          float64
total_item                         float64
subtotal_cortesia_cancel           float64
iva_cortesia_cancel                float64
ieps_cortesia_cancel               float64
total_cortesia_cancel              float64
subtotal_anulacion                 float64
iva_anulacion                      float64
ieps_anulacion                     float64
total_anulacion                    float64
clave_platillo                         str
dtype: object

In [8]:
import sys
!{sys.executable} -m pip install matplotlib

Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (3.10.8)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: numpy>=1.23 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (2.4.2)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (12.1.1)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [11]:
import matplotlib.pyplot as plt

In [10]:
df_complete_186_files.shape

(3764683, 46)

In [12]:
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", None)

In [15]:
df_complete_186_files.sample(10)

                            sucursal operating_date day_name            closing_time           captured_time  week_number  pdv_txn_id  order_id   order_type order_subtype  table_number  party_size           server    terminal capture_terminal action               item                       modifier group_type                     group                                                                     description  is_modifier  quantity  unit_price  unit_price_with_mods  cost_actual  cost_with_mods  cost_ideal  discount  subtotal_ticket  iva_ticket  ieps_ticket  total_ticket  subtotal_item  iva_item  ieps_item  total_item  subtotal_cortesia_cancel  iva_cortesia_cancel  ieps_cortesia_cancel  total_cortesia_cancel  subtotal_anulacion  iva_anulacion  ieps_anulacion  total_anulacion clave_platillo
2676366          Panem - Punto Valle     2024-10-12   sábado 2024-10-12 17:27:38.680 2024-10-12 17:26:36.170           41      151768       174  Para llevar            '-             0           1          Pruebas     SERVER1          SERVER1  Venta      OREJA NATURAL                No modificacion  Alimentos                 PAN DULCE                                                                ., OREJA NATURAL        False       1.0        45.0                  45.0      45.5035         45.5035      9.4900       0.0         136.4943     15.1724       3.3333         155.0        41.6667    0.0000     3.3333        45.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD009
549297           Panem - Hotel Kavia     2022-10-04   martes 2022-10-04 19:39:07.787 2022-10-04 19:38:05.540           40        1253        84   Restaurant            '-             4           2      Panem Kavia     SERVER1          SERVER1  Venta    CAPPUCCINO 16OZ       LECHE DESLACTOSADA LIGHT  Alimentos               MOD BEBIDAS                                                        LECHE DESLACTOSADA LIGHT         True       1.0         0.0                   0.0       0.0000          0.0000      0.0000       0.0         302.5862     48.4138       0.0000         351.0         0.0000    0.0000     0.0000         0.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          MB006
781600               Panem - Carreta     2023-10-13  viernes 2023-10-13 18:10:28.700 2023-10-13 16:39:34.880           41       70767       165  Para llevar            '-             0           1  Pruebas Carreta     SERVER1          SERVER1  Venta       SUBSIDIO TEC  MINI PIZZA PEPPERONI SUBSIDIO  Alimentos             MOD ALIMENTOS                                                   MINI PIZZA PEPPERONI SUBSIDIO         True       1.0         0.0                   0.0       0.0000          0.0000      0.0000       0.0         344.8276     55.1724       0.0000         400.0         0.0000    0.0000     0.0000         0.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          MA052
3332293        Panem - Hotel Kavia N     2024-03-17  domingo 2024-03-17 17:16:53.977 2024-03-17 17:15:49.917           11       96727       199   Restaurant            '-            11           1      Panem Kavia  Terminal 1       Terminal 1  Venta          COCA COLA                          LIGHT  Alimentos               MOD BEBIDAS                                                                           LIGHT         True       1.0         0.0                   0.0       0.0000          0.0000      0.0000       0.0         489.6552     78.3448       0.0000         568.0         0.0000    0.0000     0.0000         0.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          MB015
2646656          Panem - Punto Valle     2024-08-24   sábado 2024-08-24 17:01:25.420 2024-08-24 17:00:13.903           34      143907       133  Para llevar            '-             0           1          Pruebas     SERVER1          SERVER1  Venta        CAFE REFILL                        REGULAR  Alimentos               MOD BEBIDAS                                                                         REGULAR         True       1.0         0.0                   0.0       0.0000          0.0000      0.0000       0.0         340.7088     26.0690      14.2222         381.0         0.0000    0.0000     0.0000         0.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          MB002
2787193  Panem - Hospital Zambrano N     2025-01-14   martes 2025-01-14 13:46:13.053 2025-01-14 13:45:05.380            3      130129        68  Para llevar            '-             0           1         Zambrano     SERVER1          SERVER1  Venta   CONCHA CHOCOLATE                No modificacion  Alimentos                 PAN DULCE                                                             ., CONCHA CHOCOLATE        False       1.0        26.0                  26.0       0.4516          0.4516      7.3200       0.0          71.4879      7.5862       1.9259          81.0        24.0741    0.0000     1.9259        26.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD020
2344358        Panem - Hotel Kavia N     2025-12-23   martes 2025-12-23 11:25:02.857 2025-12-23 11:24:39.920           52      203720        27   Restaurant            '-             1           1      Panem Kavia  Terminal 1       Terminal 1  Venta   PAIN AU CHOCOLAT                No modificacion  Alimentos                 PAN DULCE                                                             ., PAIN AU CHOCOLAT        False       1.0        77.0                  77.0       1.0918          1.0918      4.9000       0.0         166.6667      0.0000      13.3333         180.0        71.2963    0.0000     5.7037        77.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD005
2540507         Panem - Plaza Nativa     2024-10-17   jueves 2024-10-17 17:21:02.967 2024-10-17 17:20:34.827           42      101108        95  Para llevar            '-             0           1        Paseo Tec        PDV1             PDV1  Venta         MOCHA 16OZ                No modificacion  Alimentos  CAFE Y BEBIDAS CALIENTES                               ., MOCHA 16OZ, LECHE DESLACTOSADA LIGHT, Cortesia        False       1.0        90.0                  90.0       5.9053          5.9053     35.5380       0.0           0.0000      0.0000       0.0000           0.0         0.0000    0.0000     0.0000         0.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0         CBC007
1584058          Panem - Punto Valle     2022-10-01   sábado 2022-10-01 19:17:45.787 2022-10-01 19:16:13.620           39       33554       199  Para llevar            '-             0           1          Pruebas     SERVER1          SERVER1  Venta      PAN DE MUERTO                No modificacion  Alimentos                 PAN DULCE                                                                ., PAN DE MUERTO        False       2.0        28.0                  28.0       0.0000          0.0000      0.0000       0.0         220.6897     35.3103       0.0000         256.0        48.2759    7.7241     0.0000        56.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD019
1993036        Panem - Hotel Kavia N     2024-08-06   martes 2024-08-06 12:56:35.950 2024-08-06 12:18:54.973           32      118224        39   Restaurant            '-            24           1      Panem Kavia  Terminal 1       Terminal 1  Venta  CHILAQUILES PANEM                No modificacion  Alimentos                 DESAYUNOS  ., CHILAQUILES PANEM, 1 SALSA VERDE, 1 POLLO CHILAQUILES INCLUIDO, 1 HUEVO +12        False       1.0       196.0                 208.0      60.5480         60.5480     37.7563       0.0         286.9093     36.2759       4.8148         328.0       179.3103   28.6897     0.0000       208.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          DE005

In [16]:
df_complete_186_files.loc[1]

sucursal                           Panem - Plaza QIN N
operating_date                     2025-12-22 00:00:00
day_name                                         lunes
closing_time                2025-12-22 08:04:56.373000
captured_time               2025-12-22 08:04:00.267000
week_number                                         52
pdv_txn_id                                      219634
order_id                                             1
order_type                                 Para llevar
order_subtype                                       '-
table_number                                         0
party_size                                           1
server                                       Plaza Qin
terminal                                    Terminal 1
capture_terminal                            Terminal 1
action                                           Venta
item                                  PAIN AU CHOCOLAT
modifier                               No modificacion
group_type                                   Alimentos
group                                        PAN DULCE
description                        ., PAIN AU CHOCOLAT
is_modifier                                      False
quantity                                           1.0
unit_price                                        77.0
unit_price_with_mods                              77.0
cost_actual                                     1.6352
cost_with_mods                                  1.6352
cost_ideal                                         4.9
discount                                           0.0
subtotal_ticket                               154.6296
iva_ticket                                         0.0
ieps_ticket                                    12.3704
total_ticket                                     167.0
subtotal_item                                  71.2963
iva_item                                           0.0
ieps_item                                       5.7037
total_item                                        77.0
subtotal_cortesia_cancel                           0.0
iva_cortesia_cancel                                0.0
ieps_cortesia_cancel                               0.0
total_cortesia_cancel                              0.0
subtotal_anulacion                                 0.0
iva_anulacion                                      0.0
ieps_anulacion                                     0.0
total_anulacion                                    0.0
clave_platillo                                   PD005
Name: 1, dtype: object

In [17]:
import os
import numpy as np

In [18]:
cwd = os.getcwd()

In [ ]:
#Top_sale_item=df_complete.groupby(["group","item"]).agg(product=("item", "count")).reset_index()

In [ ]:

#Ticket promedio
#Mes de mayor venta en los años

SyntaxError: invalid syntax (2627125745.py, line 4)

In [19]:
Top_sale_item = (
    df_complete_186_files
    .groupby("item")
    .size()
    .reset_index(name="product")
    .sort_values("product", ascending=False)
)

Top_sale_item.head(100)

                            item  product
75                   CAFE REFILL   425201
125            CHILAQUILES PANEM   264452
145                    COCA COLA   176177
94               CAPPUCCINO 16OZ   165893
178              CONCHA VAINILLA   164933
72              CAFE OLLA REFILL   149907
327                   LATTE 16OZ   140832
334                     LIMONADA   100743
330           LATTE EN LAS ROCAS    88822
161             CONCHA CHOCOLATE    77994
17                AGUA NATURA ST    74335
449                  OREO FRAPPE    61916
102            CAPPUCCINO FRAPPE    61033
137     CHOCOLATE ARTESANAL 16OZ    55042
181          CROISSANT ALMENDRAS    54329
23                 AVOCADO TOAST    51352
458             PAIN AU CHOCOLAT    47727
404                 MOCHA FRAPPE    45220
311                 JUGO NARANJA    43708
408             MUFFIN BLUEBERRY    42862
543                ROL DE CANELA    40278
188   CROISSANT DE JAMÓN Y QUESO    39975
110              CHAI LATTE 16OZ    38840
238            ENCHILADAS SUIZAS    38389
398                   MOCHA 16OZ    37899
411        MUFFIN PLATANO VEGANO    37749
283             GALLETA DE AVENA    36162
446                OREJA NATURAL    31342
343          MATCHA EN LAS ROCAS    31283
537  REBANADA CHEESECAKE TORTUGA    29645
286                 GARRA DE OSO    28655
142                CLUB SANDWICH    28164
349            MATCHA LATTE 16OZ    28099
11                          AGUA    27931
105       CAPUCCINO EN LAS ROCAS    26229
35        BAGUETTE JAMÓN SERRANO    25063
619            TARTALETA DE NUEZ    24980
501              PIZZA PEPPERONI    24781
318                   JUGO VERDE    24650
613         TARTALETA DE MANZANA    23168
610           TARTALETA DE LIMÓN    22820
109            CHAI EN LAS ROCAS    21023
195            CROISSANT NATURAL    19398
225                        DANES    18607
431            OMELETTE DE JAMÓN    18384
401           MOCHA EN LAS ROCAS    18378
28              BAGUETTE CAPRESE    18281
241               ENSALADA CESAR    18257
587                 SUBSIDIO TEC    17913
569                  SOPA TOMATE    17546
555      SANDWICH ENSALADA POLLO    16508
136           CHIPS LOCAL SNACKS    15308
97                CAPPUCCINO 8OZ    15086
648                     TÉ VERDE    14617
260               ESPRESSO DOBLE    14292
561                        SCONE    14226
198               CROISSANT ROLL    14168
185         CROISSANT DE BERRIES    13880
234                       ECLAIR    12413
429      OMELETTE DE CHAMPIÑONES    12405
639              TISANA FRIA POP    12313
599                  TARO FRAPPE    11817
115            CHAI LATTE FRAPPE    10799
48                       BISQUET    10772
433            OMELETTE ESPINACA     9678
657                     VASO BIO     9430
661                  VELVET SODA     9350
358             MINI CHILAQUILES     8659
605          TARTALETA DE FRESAS     8303
199                CROQUE MADAME     8265
278                 FRENCH TOAST     8198
632                  TISANA 16OZ     8019
121          CHEESECAKE DE FRESA     7665
177                  CONCHA UBER     7404
350          MATCHA LATTE FRAPPE     7383
317                JUGO TROPICAL     7303
558     SANDWITCH ENSALADA POLLO     7184
616           TARTALETA DE MORAS     7181
572                    SOURDOUGH     6955
264              ESPRESSO SIMPLE     6473
576           SOURDOUGH 5 QUESOS     6453
443           OREJA DE CHOCOLATE     6116
70                  CAFE OFICIAL     6043
87               CAJA 10 CONCHAS     5924
22                       ALFAJOR     5891
508                        POLLO     5852
126     CHILAQUILES PANEM CHICOS     5654
380           MINI PIZZA DEL DIA     5501
488               PIZZA 5 QUESOS     5440
540              REBANADA SACHER     5418
131       CHILAQUILES PANEM UBER     5332
60                       BROWNIE     5237
383     MINI PIZZA PEPPERONI SUB     4711
333               LECHE ALMENDRA     4691
462                PAN DE MUERTO     4684
385        MINI PIZZA VEGGIE SUB     4414
167                 CONCHA RAPPI     4321
49       BISQUET CON MANTEQUILLA     4237
361  MINI CHILAQUILES VERDES SUB     4084
228                         DONA     4041

In [31]:
Top_sale_item

                              group                                                            item  product
3          CAFE Y BEBIDAS CALIENTES                                                     CAFE REFILL   213557
335                     MOD BEBIDAS                                                     CAFE REFILL   211644
544                       PAN DULCE                                                 CONCHA VAINILLA   164933
2          CAFE Y BEBIDAS CALIENTES                                                CAFE OLLA REFILL   149309
259                   MOD ALIMENTOS                                               CHILAQUILES PANEM   125207
72                        DESAYUNOS                                               CHILAQUILES PANEM   117006
221           JUGOS Y BEBIDAS FRIAS                                                        LIMONADA   100743
206           JUGOS Y BEBIDAS FRIAS                                                       COCA COLA    88959
339                     MOD BEBIDAS                                                 CAPPUCCINO 16OZ    88240
366                     MOD BEBIDAS                                                       COCA COLA    87218
531                       PAN DULCE                                                CONCHA CHOCOLATE    77994
5          CAFE Y BEBIDAS CALIENTES                                                 CAPPUCCINO 16OZ    77653
388                     MOD BEBIDAS                                                      LATTE 16OZ    76805
23         CAFE Y BEBIDAS CALIENTES                                                      LATTE 16OZ    64027
545                       PAN DULCE                                             CROISSANT ALMENDRAS    54329
391                     MOD BEBIDAS                                              LATTE EN LAS ROCAS    51052
199           JUGOS Y BEBIDAS FRIAS                                                  AGUA NATURA ST    49715
573                       PAN DULCE                                                PAIN AU CHOCOLAT    47727
67                        DESAYUNOS                                                   AVOCADO TOAST    47029
216           JUGOS Y BEBIDAS FRIAS                                                    JUGO NARANJA    43708
560                       PAN DULCE                                                MUFFIN BLUEBERRY    42862
588                       PAN DULCE                                                   ROL DE CANELA    40278
80                        DESAYUNOS                                               ENCHILADAS SUIZAS    38389
76                        DESAYUNOS                                      CROISSANT DE JAMÓN Y QUESO    38358
220           JUGOS Y BEBIDAS FRIAS                                              LATTE EN LAS ROCAS    37770
561                       PAN DULCE                                           MUFFIN PLATANO VEGANO    37749
347                     MOD BEBIDAS                                               CAPPUCCINO FRAPPE    36856
551                       PAN DULCE                                                GALLETA DE AVENA    36162
433                     MOD BEBIDAS                                                     OREO FRAPPE    35782
572                       PAN DULCE                                                   OREJA NATURAL    31342
782                      REPOSTERIA                                     REBANADA CHEESECAKE TORTUGA    29645
552                       PAN DULCE                                                    GARRA DE OSO    28655
41                          COMIDAS                                                   CLUB SANDWICH    28164
361                     MOD BEBIDAS                                        CHOCOLATE ARTESANAL 16OZ    27545
10         CAFE Y BEBIDAS CALIENTES                                        CHOCOLATE ARTESANAL 16OZ    27492
226           JUGOS Y BEBIDAS FRIAS                                                     OREO FRAPPE    26134
429                     MOD BEBIDAS                                                    MOCHA FRAPPE    25998
39                          COMIDAS                                          BAGUETTE JAMÓN SERRANO    25063
790                      REPOSTERIA                                               TARTALETA DE NUEZ    24980
219           JUGOS Y BEBIDAS FRIAS                                                      JUGO VERDE    24650
325                     MOD BEBIDAS                                                  AGUA NATURA ST    24620
201           JUGOS Y BEBIDAS FRIAS                                               CAPPUCCINO FRAPPE    24177
788                      REPOSTERIA                                            TARTALETA DE MANZANA    23125
787                      REPOSTERIA                                              TARTALETA DE LIMÓN    22820
648                           PIZZA                                                 PIZZA PEPPERONI    20637
482           NATIVA TEMPORALCOMIDA                                               CHILAQUILES PANEM    20607
8          CAFE Y BEBIDAS CALIENTES                                                 CHAI LATTE 16OZ    19535
547                       PAN DULCE                                               CROISSANT NATURAL    19398
352                     MOD BEBIDAS                                                 CHAI LATTE 16OZ    19305
28         CAFE Y BEBIDAS CALIENTES                                                      MOCHA 16OZ    19292
225           JUGOS Y BEBIDAS FRIAS                                                    MOCHA FRAPPE    19222
549                       PAN DULCE                                                           DANES    18607
423                     MOD BEBIDAS                                                      MOCHA 16OZ    18607
38                          COMIDAS                                                BAGUETTE CAPRESE    18281
45                          COMIDAS                                                  ENSALADA CESAR    18257
61                          COMIDAS                                                     SOPA TOMATE    17546
59                          COMIDAS                                         SANDWICH ENSALADA POLLO    16508
93                        DESAYUNOS                                               OMELETTE DE JAMÓN    15810
222           JUGOS Y BEBIDAS FRIAS                                             MATCHA EN LAS ROCAS    15802
394                     MOD BEBIDAS                                             MATCHA EN LAS ROCAS    15481
350                     MOD BEBIDAS                                          CAPUCCINO EN LAS ROCAS    14794
16         CAFE Y BEBIDAS CALIENTES                                                  ESPRESSO DOBLE    14286
548                       PAN DULCE                                                  CROISSANT ROLL    14165
25         CAFE Y BEBIDAS CALIENTES                                               MATCHA LATTE 16OZ    14135
197           JUGOS Y BEBIDAS FRIAS                                                            AGUA    13995
400                     MOD BEBIDAS                                               MATCHA LATTE 16OZ    13964
324                     MOD BEBIDAS                                                            AGUA    13936
654          PRODUCTOS DE TEMPORADA                                            CROISSANT DE BERRIES    13880
202           JUGOS Y BEBIDAS FRIAS                                          CAPUCCINO EN LAS ROCAS    11435
92                        DESAYUNOS                                         OMELETTE DE CHAMPIÑONES    11170
203           JUGOS Y BEBIDAS FRIAS                                               CHAI EN LAS ROCAS    10625
351                     MOD BEBIDAS                                               CHAI EN LAS ROCAS    10397
625               PANEM MARKETPLACE                                              CHIPS LOCAL SNACKS     9823
94                        DESAYUNOS                                               OMELETTE ESPINACA     9667
195                          EXTRAS                                                        VASO BIO     9430
426                     MOD BEBIDAS                                              MOCHA EN LAS ROCAS     9211
224           JUGOS Y BEBIDAS FRIAS                                              MOCHA EN LAS ROCAS     9167
321                   MOD ALIMENTOS                                                    SUBSIDIO TEC     8802
785                      REPOSTERIA                                             TARTALETA DE FRESAS     8303
78                        DESAYUNOS                                                   CROQUE MADAME     8265
81                        DESAYUNOS                                                    FRENCH TOAST     8198
524                       PAN DULCE                                                         BISQUET     8015
342                     MOD BEBIDAS                                                  CAPPUCCINO 8OZ     7916
65                          COMIDAS                                                    SUBSIDIO TEC     7688
651          PRODUCTOS DE TEMPORADA                                             CHEESECAKE DE FRESA     7665
37         CAFE Y BEBIDAS CALIENTES                                                        TÉ VERDE     7320
218           JUGOS Y BEBIDAS FRIAS                                                   JUGO TROPICAL     7303
591                       PAN DULCE                                                           SCONE     7226
60                          COMIDAS                                        SANDWITCH ENSALADA POLLO     7184
789                      REPOSTERIA                                              TARTALETA DE MORAS     7181
6          CAFE Y BEBIDAS CALIENTES                                                  CAPPUCCINO 8OZ     7170
313                   MOD ALIMENTOS                                                           SCONE     7000
618                      PAN SALADO                                                       SOURDOUGH     6955
469                     MOD BEBIDAS                                                 TISANA FRIA POP     6828
456                     MOD BEBIDAS                                                     TARO FRAPPE     6569
18         CAFE Y BEBIDAS CALIENTES                                                 ESPRESSO SIMPLE     6473
63                          COMIDAS                                              SOURDOUGH 5 QUESOS     6453
777                      REPOSTERIA                                                          ECLAIR     6333
571                       PAN DULCE                                              OREJA DE CHOCOLATE     6116
277                   MOD ALIMENTOS                                                          ECLAIR     6080
1          CAFE Y BEBIDAS CALIENTES                                                    CAFE OFICIAL     6043
182                          EXTRAS                                                           POLLO     5852
357                     MOD BEBIDAS                                               CHAI LATTE FRAPPE     5796
522                       PAN DULCE                                                         ALFAJOR     5750
474                     MOD BEBIDAS                                                        TÉ VERDE     5675
242           JUGOS Y BEBIDAS FRIAS                                                 TISANA FRIA POP     5485
479                 MOD MARKETPLACE                                              CHIPS LOCAL SNACKS     5484
644                           PIZZA                                                  PIZZA 5 QUESOS     5440
784                      REPOSTERIA                                                 REBANADA SACHER     5418
234           JUGOS Y BEBIDAS FRIAS                                                     TARO FRAPPE     5248
526                       PAN DULCE                                                         BROWNIE     5237
204           JUGOS Y BEBIDAS FRIAS                                               CHAI LATTE FRAPPE     5003
281                   MOD ALIMENTOS                                                MINI CHILAQUILES     5000
173                          EXTRAS                                                  LECHE ALMENDRA     4691
244           JUGOS Y BEBIDAS FRIAS                                                     VELVET SODA     4686
574                       PAN DULCE                                                   PAN DE MUERTO     4684
476                     MOD BEBIDAS                                                     VELVET SODA     4664
246                   MOD ALIMENTOS                                                   AVOCADO TOAST     4323
303                   MOD ALIMENTOS                                                 PIZZA PEPPERONI     4144
401                     MOD BEBIDAS                                             MATCHA LATTE FRAPPE     4050
550                       PAN DULCE                                                            DONA     4041
189                          EXTRAS                                             SHOT ESPRESSO EXTRA     4037
34         CAFE Y BEBIDAS CALIENTES                                                     TISANA 16OZ     4028
462                     MOD BEBIDAS                                                     TISANA 16OZ     3991
911                  UBER PAN DULCE                                                     CONCHA UBER     3752
260                   MOD ALIMENTOS                                        CHILAQUILES PANEM CHICOS     3652
643                           PIZZA                                                  PIZZA 4 QUESOS     3507
64                          COMIDAS                                                SOURDOUGH SALMÓN     3396
223           JUGOS Y BEBIDAS FRIAS                                             MATCHA LATTE FRAPPE     3333
578                       PAN DULCE                                             PAN DE MUERTO PANEM     3290
148                          EXTRAS                                                         ADEREZO     3136
88                        DESAYUNOS                                                MINI CHILAQUILES     3087
46                          COMIDAS                                                   ENSALADA COBB     3051
101                       DESAYUNOS                                                 QUICHE LORRAINE     3031
217           JUGOS Y BEBIDAS FRIAS                                                       JUGO ROJO     3024
527                       PAN DULCE                                                 CAJA 10 CONCHAS     3021
69                        DESAYUNOS                                   BLUEBERRY BANANA BOWL GRANOLA     2964
655          PRODUCTOS DE TEMPORADA                                                 OREJA CHOCOLATE     2954
89                        DESAYUNOS                                        MINI CHILAQUILES CARRETA     2950
264                   MOD ALIMENTOS                                          CHILAQUILES PANEM UBER     2853
171                          EXTRAS                                                           HUEVO     2789
99                        DESAYUNOS                                               QUICHE FLORENTINE     2787
62                          COMIDAS                                              SOURDOUGH 4 QUESOS     2784
237           JUGOS Y BEBIDAS FRIAS                                                TE HELADO REFILL     2777
641                           PIZZA                                              MINI PIZZA DEL DIA     2775
254                   MOD ALIMENTOS                                                         BISQUET     2757
196                          EXTRAS                                                       VEGETALES     2750
243           JUGOS Y BEBIDAS FRIAS                                                      VASO LECHE     2733
287                   MOD ALIMENTOS                                              MINI PIZZA DEL DIA     2726
601                      PAN SALADO                                                 BAGUETTE PETITE     2723
523                       PAN DULCE                                                       BERLINESA     2589
372                     MOD BEBIDAS                                                     CONCHA UBER     2589
299                   MOD ALIMENTOS                                               OMELETTE DE JAMÓN     2570
79                        DESAYUNOS                                                 CROQUE MONSIEUR     2555
881                  UBER DESAYUNOS                                          CHILAQUILES PANEM UBER     2479
68                        DESAYUNOS                                         BISQUET CON MANTEQUILLA     2454
102                       DESAYUNOS                                         SOURDOUGH AVOCADO TOAST     2332
48                          COMIDAS                                                  ENSALADA PANEM     2300
77                        DESAYUNOS                                             CROISSANT DE SALMÓN     2250
194                          EXTRAS                                                       VAINILLAA     2184
736                 RAPPI PAN DULCE                                                    CONCHA RAPPI     2170
103                       DESAYUNOS                                                  SOURDOUGH EGGS     2154
200           JUGOS Y BEBIDAS FRIAS                                             AGUA SAN PELLEGRINO     2091
262                   MOD ALIMENTOS                                       CHILAQUILES PANEM GRANDES     2084
183                          EXTRAS                                                           QUESO     2034
120                     ESPECIALES-                                        COMBO NATIVA CONCHA CAFÉ     2019
73                        DESAYUNOS                                        CHILAQUILES PANEM CHICOS     2002
213           JUGOS Y BEBIDAS FRIAS                                 ESPRESSO AMERICANO EN LAS ROCAS     1964
645                           PIZZA                                                   PIZZA DIAVOLO     1943
172                          EXTRAS                                                   JAMÓN SERRANO     1912
579                       PAN DULCE                                           PAN DE MUERTO RELLENO     1865
525                       PAN DULCE                                                         BRIOCHE     1862
145                          EXTRAS                                                      '+HUEVOO14     1814
255                   MOD ALIMENTOS                                         BISQUET CON MANTEQUILLA     1783
534                       PAN DULCE                                                    CONCHA PRIDE     1782
647                           PIZZA                                                     PIZZA PANEM     1735
231           JUGOS Y BEBIDAS FRIAS                                            Smoothie Bananaberry     1728
646                           PIZZA                                             PIZZA JAMON SERRANO     1725
256                   MOD ALIMENTOS                                                 CAJA 10 CONCHAS     1712
453                     MOD BEBIDAS                                            Smoothie Bananaberry     1709
149                          EXTRAS                                                        AGUACATE     1700
82                        DESAYUNOS                                        HAM CHEESE SANDWICH ROLL     1673

In [20]:
top_sucursal = (
    df_complete_186_files
    .groupby("sucursal")
    .size()
    .reset_index(name="orders")
    .sort_values("orders", ascending=False)
)

# 2) Sucursal + order_type (most to least)
sucursal_order_type = (
    df_complete_186_files
    .groupby(["sucursal", "order_type"])
    .size()
    .reset_index(name="orders")
    .sort_values("orders", ascending=False)
)

top_sucursal.head(10)
sucursal_order_type.head(20)

                       sucursal   order_type  orders
11        Panem - Hotel Kavia N   Restaurant  592305
21          Panem - Punto Valle   Restaurant  529261
20          Panem - Punto Valle  Para llevar  415085
6   Panem - Hospital Zambrano N  Para llevar  274199
19          Panem - Plaza QIN N   Restaurant  272388
9           Panem - Hotel Kavia   Restaurant  242818
12         Panem - La Carreta N  Para llevar  222277
17            Panem - Plaza QIN   Restaurant  218754
4     Panem - Hospital Zambrano  Para llevar  193270
0               Panem - Carreta  Para llevar  170947
16            Panem - Plaza QIN  Para llevar  130610
14         Panem - Plaza Nativa  Para llevar  118137
18          Panem - Plaza QIN N  Para llevar  113128
15         Panem - Plaza Nativa   Restaurant   76374
7   Panem - Hospital Zambrano N   Restaurant   61443
5     Panem - Hospital Zambrano   Restaurant   58034
2            Panem - Credi Club  Para llevar   29736
3            Panem - Credi Club   Restaurant   18643
8           Panem - Hotel Kavia  Para llevar   11336
10        Panem - Hotel Kavia N  Para llevar   10303

In [21]:
#dia y hora pico de ventas



df = df_complete_186_files.copy()
df["captured_time"] = pd.to_datetime(df["captured_time"], errors="coerce")
df = df.dropna(subset=["captured_time"])

df["month"] = df["captured_time"].dt.to_period("M")
df["date"] = df["captured_time"].dt.date
df["day_name"] = df["captured_time"].dt.day_name()
df["hour"] = df["captured_time"].dt.hour

# --- Day with highest MEAN sales in each month ---
# sales per date
daily_sales = (
    df.groupby(["month", "date"])
    .size()
    .reset_index(name="sales")
)
daily_sales["day_name"] = pd.to_datetime(daily_sales["date"]).dt.day_name()

# mean sales by day_name inside each month
day_mean = (
    daily_sales.groupby(["month", "day_name"])["sales"]
    .mean()
    .reset_index(name="mean_sales_day")
)

top_day_per_month = (
    day_mean.sort_values(["month", "mean_sales_day"], ascending=[True, False])
    .drop_duplicates("month")
)

# --- Hour with highest MEAN sales in each month ---
# sales per date-hour
hourly_sales = (
    df.groupby(["month", "date", "hour"])
    .size()
    .reset_index(name="sales")
)

# mean sales by hour inside each month
hour_mean = (
    hourly_sales.groupby(["month", "hour"])["sales"]
    .mean()
    .reset_index(name="mean_sales_hour")
)

top_hour_per_month = (
    hour_mean.sort_values(["month", "mean_sales_hour"], ascending=[True, False])
    .drop_duplicates("month")
)

# Final table
result = top_day_per_month.merge(top_hour_per_month, on="month", how="inner")
result = result[["month", "day_name", "mean_sales_day", "hour", "mean_sales_hour"]]
result = result.sort_values("month")

result

      month   day_name  mean_sales_day  hour  mean_sales_hour
0   2022-01     Monday           11.00    20        11.000000
1   2022-02   Saturday          958.00    18        71.392857
2   2022-03   Saturday         1045.00    10        93.709677
3   2022-04   Saturday         1027.00    18        84.566667
4   2022-05    Tuesday         1608.60    10       176.354839
5   2022-06     Friday         1705.75    10       175.833333
6   2022-07   Saturday         1588.00    10       164.870968
7   2022-08   Thursday         2016.75    11       195.677419
8   2022-09   Thursday         2184.80    10       209.700000
9   2022-10   Saturday         3438.40    10       299.258065
10  2022-11     Friday         2159.25    11       215.033333
11  2022-12    Tuesday         1821.00    11       175.032258
12  2023-01   Saturday         2061.25    11       169.645161
13  2023-02   Saturday         2252.00    11       202.857143
14  2023-03     Friday         2252.20    10       224.677419
15  2023-04   Thursday         2291.00    11       197.066667
16  2023-05   Saturday         3579.00    10       327.548387
17  2023-06   Saturday         3316.50    10       312.666667
18  2023-07   Saturday         3364.20    10       304.387097
19  2023-08   Saturday         3431.00    10       320.645161
20  2023-09   Saturday         3660.80    10       337.633333
21  2023-10   Saturday         3521.50    10       319.870968
22  2023-11   Saturday         3031.00    11       233.800000
23  2023-12   Saturday         2794.40    11       252.709677
24  2024-01   Saturday         2947.25    11       229.677419
25  2024-02  Wednesday         2137.75    10       189.896552
26  2024-03   Saturday         3390.20    10       326.935484
27  2024-04   Saturday         3301.00    11       304.800000
28  2024-05   Saturday         3477.00    10       328.580645
29  2024-06   Saturday         2977.80    10       314.517241
30  2024-07   Saturday         3097.50    10       286.580645
31  2024-08   Saturday         3227.00    10       336.903226
32  2024-09   Saturday         3211.00    10       324.800000
33  2024-10   Saturday         3414.75    10       331.709677
34  2024-11   Saturday         3844.60    10       389.466667
35  2024-12   Saturday         3256.25    10       332.466667
36  2025-01   Saturday         4351.25    11       335.161290
37  2025-02   Saturday         3704.75    11       366.214286
38  2025-03   Saturday         3709.60    10       359.258065
39  2025-04   Saturday         3141.75    10       317.166667
40  2025-05   Saturday         3568.00    10       342.225806
41  2025-06   Saturday         3238.50    10       317.566667
42  2025-07   Saturday         3090.25    10       293.096774
43  2025-08   Saturday         3124.60    10       325.322581
44  2025-09   Saturday         3128.50    10       328.166667
45  2025-10   Saturday         3317.25    10       352.548387
46  2025-11     Friday         4786.50    11       498.300000
47  2025-12   Saturday         5139.75    10       509.580645
48  2026-01   Saturday         6486.00    11       539.935484
49  2026-02   Saturday         9858.00    10       777.416667

In [22]:

ORDER_ID_COL = "order_id"
AMOUNT_COL = "total_ticket"          # total amount per row/item
DATE_COL = "captured_time"

df = df_complete_186_files.copy()
df[DATE_COL] = pd.to_datetime(df[DATE_COL], errors="coerce")
df = df.dropna(subset=[DATE_COL])

# Optional: keep only valid paid sales
# df = df[(df[AMOUNT_COL] > 0) & (df["status"] == "PAID")]

# Mean ticket overall (order total taken once per order)
ticket_per_order = df.groupby(ORDER_ID_COL)[AMOUNT_COL].first()
mean_ticket_overall = ticket_per_order.mean()

# Mean ticket by month
mean_ticket_month = (
    df.assign(month=df[DATE_COL].dt.to_period("M"))
      .groupby(["month", ORDER_ID_COL])[AMOUNT_COL].first()
      .reset_index()
      .groupby("month")[AMOUNT_COL].mean()
      .reset_index(name="mean_ticket")
      .sort_values("month")
)

mean_ticket_overall, mean_ticket_month.head(50)

(np.float64(177.3945945945946),
       month  mean_ticket
 0   2022-01   396.500000
 1   2022-02   161.713565
 2   2022-03   183.381034
 3   2022-04   171.987395
 4   2022-05   152.395000
 5   2022-06   166.084821
 6   2022-07   172.130841
 7   2022-08   152.061594
 8   2022-09   106.220760
 9   2022-10   114.265347
 10  2022-11   122.837793
 11  2022-12   180.659636
 12  2023-01   186.415730
 13  2023-02   185.652632
 14  2023-03   146.106991
 15  2023-04   181.956747
 16  2023-05   186.862462
 17  2023-06   173.752787
 18  2023-07   193.426667
 19  2023-08   173.905300
 20  2023-09   152.232450
 21  2023-10   163.876221
 22  2023-11   261.446104
 23  2023-12   264.553898
 24  2024-01   270.243450
 25  2024-02   126.324865
 26  2024-03   146.364780
 27  2024-04   283.043854
 28  2024-05   345.687347
 29  2024-06   288.434426
 30  2024-07   260.881081
 31  2024-08   136.483395
 32  2024-09   116.610487
 33  2024-10   125.438796
 34  2024-11   143.498777
 35  2024-12   163.681605
 36  2025-01   174.354341
 37  2025-02   174.707143
 38  2025-03   179.812000
 39  2025-04   145.396721
 40  2025-05   191.523026
 41  2025-06   191.533824
 42  2025-07   176.035179
 43  2025-08   160.058900
 44  2025-09   131.003716
 45  2025-10   117.909091
 46  2025-11   230.889049
 47  2025-12   164.894737
 48  2026-01   242.655598
 49  2026-02   337.131061)

In [23]:
df_complete_186_files.head()

              sucursal operating_date day_name            closing_time           captured_time  week_number  pdv_txn_id  order_id   order_type order_subtype  table_number  party_size     server    terminal capture_terminal action                  item         modifier group_type                     group              description  is_modifier  quantity  unit_price  unit_price_with_mods  cost_actual  cost_with_mods  cost_ideal  discount  subtotal_ticket  iva_ticket  ieps_ticket  total_ticket  subtotal_item  iva_item  ieps_item  total_item  subtotal_cortesia_cancel  iva_cortesia_cancel  ieps_cortesia_cancel  total_cortesia_cancel  subtotal_anulacion  iva_anulacion  ieps_anulacion  total_anulacion clave_platillo
0  Panem - Plaza QIN N     2025-12-22    lunes 2025-12-22 08:04:56.373 2025-12-22 08:03:54.367           52      219634         1  Para llevar            '-             0           1  Plaza Qin  Terminal 1       Terminal 1  Venta  TARTALETA DE MANZANA  No modificacion  Alimentos                REPOSTERIA  ., TARTALETA DE MANZANA        False       1.0        90.0                  90.0       1.0000          1.0000     36.4500       0.0         154.6296      0.0000      12.3704         167.0        83.3333    0.0000     6.6667        90.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          RE009
1  Panem - Plaza QIN N     2025-12-22    lunes 2025-12-22 08:04:56.373 2025-12-22 08:04:00.267           52      219634         1  Para llevar            '-             0           1  Plaza Qin  Terminal 1       Terminal 1  Venta      PAIN AU CHOCOLAT  No modificacion  Alimentos                 PAN DULCE      ., PAIN AU CHOCOLAT        False       1.0        77.0                  77.0       1.6352          1.6352      4.9000       0.0         154.6296      0.0000      12.3704         167.0        71.2963    0.0000     5.7037        77.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD005
2  Panem - Plaza QIN N     2025-12-22    lunes 2025-12-22 08:05:58.817 2025-12-22 08:05:06.900           52      219635         2  Para llevar            '-             0           1  Plaza Qin  Terminal 1       Terminal 1  Venta      CAFE OLLA REFILL  No modificacion  Alimentos  CAFE Y BEBIDAS CALIENTES      ., CAFE OLLA REFILL        False       1.0        55.0                  55.0       0.0000          0.0000      3.4299       0.0          71.4879      7.5862       1.9259          81.0        47.4138    7.5862     0.0000        55.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0         CBC020
3  Panem - Plaza QIN N     2025-12-22    lunes 2025-12-22 08:05:58.817 2025-12-22 08:05:08.707           52      219635         2  Para llevar            '-             0           1  Plaza Qin  Terminal 1       Terminal 1  Venta       CONCHA VAINILLA  No modificacion  Alimentos                 PAN DULCE       ., CONCHA VAINILLA        False       1.0        26.0                  26.0       2.1257          2.1257      7.3200       0.0          71.4879      7.5862       1.9259          81.0        24.0741    0.0000     1.9259        26.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0          PD001
4  Panem - Plaza QIN N     2025-12-22    lunes 2025-12-22 08:06:42.833 2025-12-22 08:06:10.007           52      219636         3  Para llevar            '-             0           1  Plaza Qin  Terminal 1       Terminal 1  Venta      CAFE OLLA REFILL  No modificacion  Alimentos  CAFE Y BEBIDAS CALIENTES      ., CAFE OLLA REFILL        False       1.0        55.0                  55.0       0.0000          0.0000      3.4299       0.0          47.4138      7.5862       0.0000          55.0        47.4138    7.5862     0.0000        55.0                       0.0                  0.0                   0.0                    0.0                 0.0            0.0             0.0              0.0         CBC020

In [24]:
df_complete_186_files.dtypes

sucursal                               str
operating_date              datetime64[us]
day_name                               str
closing_time                datetime64[us]
captured_time               datetime64[us]
week_number                          int64
pdv_txn_id                           int64
order_id                             int64
order_type                             str
order_subtype                          str
table_number                         int64
party_size                           int64
server                                 str
terminal                               str
capture_terminal                       str
action                                 str
item                                   str
modifier                               str
group_type                             str
group                                  str
description                            str
is_modifier                           bool
quantity                           float64
unit_price                         float64
unit_price_with_mods               float64
cost_actual                        float64
cost_with_mods                     float64
cost_ideal                         float64
discount                           float64
subtotal_ticket                    float64
iva_ticket                         float64
ieps_ticket                        float64
total_ticket                       float64
subtotal_item                      float64
iva_item                           float64
ieps_item                          float64
total_item                         float64
subtotal_cortesia_cancel           float64
iva_cortesia_cancel                float64
ieps_cortesia_cancel               float64
total_cortesia_cancel              float64
subtotal_anulacion                 float64
iva_anulacion                      float64
ieps_anulacion                     float64
total_anulacion                    float64
clave_platillo                         str
dtype: object