In [22]:

import glob
import pandas as pd

In [ ]:


### Load the dataset:
df = pd.read_csv('Complete Data/Carreta/detail_Panem-Carreta_2022-02-18_2022-05-07.csv')




pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

### Display the first 5 rows of the dataset:
df.head()

,sucursal,operating_date,day_name,closing_time,captured_time,week_number,pdv_txn_id,order_id,order_type,order_subtype,table_number,party_size,server,terminal,capture_terminal,action,item,modifier,group_type,group,description,is_modifier,quantity,unit_price,unit_price_with_mods,cost_actual,cost_with_mods,cost_ideal,discount,subtotal_ticket,iva_ticket,ieps_ticket,total_ticket,subtotal_item,iva_item,ieps_item,total_item,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion,clave_platillo
0,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:48.077000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,NaN,Alimentos,DESAYUNOS,"CHILAQUILES PANEM, SALSA ROJA, HUEVO +12, .,** SIN QUESO YCREMA **",False,1.0,189.0,201.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,173.2759,27.7241,0.0,201.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE005
1,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:52.763000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,SALSA ROJA,Alimentos,MOD ALIMENTOS,SALSA ROJA,True,1.0,0.0,0.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,0.0000,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA001
2,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:53.950000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,HUEVO +12,Alimentos,MOD ALIMENTOS,HUEVO +12,True,1.0,12.0,0.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,10.3448,1.6552,0.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA003
3,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153000,2022-02-18 08:22:25.670000,7,2,2,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CAPPUCCINO 16OZ,NaN,Alimentos,CAFE Y BEBIDAS CALIENTES,"CAPPUCCINO 16OZ, LECHE ENTERA, .",False,1.0,89.0,89.0,0.0,0.0,0.0,0.0,118.9655,19.0345,0.0,138.0,76.7241,12.2759,0.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC003
4,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153000,2022-02-18 08:22:30.090000,7,2,2,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CAPPUCCINO 16OZ,LECHE ENTERA,Alimentos,MOD BEBIDAS,LECHE ENTERA,True,1.0,0.0,0.0,0.0,0.0,0.0,0.0,118.9655,19.0345,0.0,138.0,0.0000,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MB005

In [18]:
df.shape

(21524, 46)

In [17]:
import pandas as pd

### Load the dataset:
df = pd.read_csv('Complete Data/Carreta/detail_Panem-Carreta_2022-02-18_2022-05-07.csv')

### Display the first 5 rows of the dataset:
df.head()

,sucursal,operating_date,day_name,closing_time,captured_time,week_number,pdv_txn_id,order_id,order_type,order_subtype,table_number,party_size,server,terminal,capture_terminal,action,item,modifier,group_type,group,description,is_modifier,quantity,unit_price,unit_price_with_mods,cost_actual,cost_with_mods,cost_ideal,discount,subtotal_ticket,iva_ticket,ieps_ticket,total_ticket,subtotal_item,iva_item,ieps_item,total_item,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion,clave_platillo
0,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:48.077000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,NaN,Alimentos,DESAYUNOS,"CHILAQUILES PANEM, SALSA ROJA, HUEVO +12, .,** SIN QUESO YCREMA **",False,1.0,189.0,201.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,173.2759,27.7241,0.0,201.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE005
1,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:52.763000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,SALSA ROJA,Alimentos,MOD ALIMENTOS,SALSA ROJA,True,1.0,0.0,0.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,0.0000,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA001
2,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887000,2022-02-18 08:17:53.950000,7,1,1,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CHILAQUILES PANEM GRANDES,HUEVO +12,Alimentos,MOD ALIMENTOS,HUEVO +12,True,1.0,12.0,0.0,0.0,0.0,0.0,0.0,173.2759,27.7241,0.0,201.0,10.3448,1.6552,0.0,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA003
3,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153000,2022-02-18 08:22:25.670000,7,2,2,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CAPPUCCINO 16OZ,NaN,Alimentos,CAFE Y BEBIDAS CALIENTES,"CAPPUCCINO 16OZ, LECHE ENTERA, .",False,1.0,89.0,89.0,0.0,0.0,0.0,0.0,118.9655,19.0345,0.0,138.0,76.7241,12.2759,0.0,89.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC003
4,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153000,2022-02-18 08:22:30.090000,7,2,2,Para llevar,'-,NaN,1,Pruebas Carreta,SERVER1,SERVER1,Venta,CAPPUCCINO 16OZ,LECHE ENTERA,Alimentos,MOD BEBIDAS,LECHE ENTERA,True,1.0,0.0,0.0,0.0,0.0,0.0,0.0,118.9655,19.0345,0.0,138.0,0.0000,0.0000,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MB005

Total files: 0

ValueError: No objects to concatenate