In [1]:
# ...existing code...
import glob, os
import pandas as pd

path = "/Users/diego/Documents/ChallengeAI/Complete Data"
csv_files = sorted(glob.glob(os.path.join(path, "*.csv")))
print(f"Found {len(csv_files)} CSV files in: {path}")

def safe_read(f):
    try:
        return pd.read_csv(f, low_memory=False)
    except Exception as e:
        print(f"Error reading {f}: {e}")
        return None

dfs = []
for f in csv_files:
    df = safe_read(f)
    if df is not None:
        df["_source_file"] = os.path.basename(f)
        dfs.append(df)

if not dfs:
    print("No CSVs loaded.")
else:
    # Concatenate (apilar filas). Útil cuando los CSV tienen las mismas columnas.
    df_all = pd.concat(dfs, ignore_index=True, sort=False)

    # Parsear columnas datetime comunes si existen
    for col in ["operating_date", "closing_time", "captured_time"]:
        if col in df_all.columns:
            df_all[col] = pd.to_datetime(df_all[col], errors="coerce")

    # Asignar al df1 usado en el notebook
    df1 = df_all
    print("df1.shape:", df1.shape)
    display(df1.head())

# Si en su lugar quieres hacer joins por una key (merge sucesivo), puedes usar:
def merge_on_key(files, key, how="outer", suffixes=("_x","_y")):
    dfsm = [pd.read_csv(f, low_memory=False) for f in files]
    out = dfsm[0]
    for d in dfsm[1:]:
        out = out.merge(d, on=key, how=how, suffixes=suffixes)
    return out
# ...existing code...

Found 186 CSV files in: /Users/diego/Documents/ChallengeAI/Complete Data

/var/folders/h4/srr2qc116dg83xvd0rkbfh6c0000gn/T/ipykernel_69926/77780185.py:27: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_all = pd.concat(dfs, ignore_index=True, sort=False)

df1.shape: (3764683, 47)

,sucursal,operating_date,day_name,closing_time,captured_time,week_number,pdv_txn_id,order_id,order_type,order_subtype,...,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion,clave_platillo,_source_file
0,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:48.077,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE005,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
1,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:52.763,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA001,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
2,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:53.950,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA003,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
3,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153,2022-02-18 08:22:25.670,7,2,2,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC003,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
4,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153,2022-02-18 08:22:30.090,7,2,2,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MB005,detail_Panem-Carreta_2022-02-18_2022-05-07.csv

In [2]:
df1.columns

Index(['sucursal', 'operating_date', 'day_name', 'closing_time',
       'captured_time', 'week_number', 'pdv_txn_id', 'order_id', 'order_type',
       'order_subtype', 'table_number', 'party_size', 'server', 'terminal',
       'capture_terminal', 'action', 'item', 'modifier', 'group_type', 'group',
       'description', 'is_modifier', 'quantity', 'unit_price',
       'unit_price_with_mods', 'cost_actual', 'cost_with_mods', 'cost_ideal',
       'discount', 'subtotal_ticket', 'iva_ticket', 'ieps_ticket',
       'total_ticket', 'subtotal_item', 'iva_item', 'ieps_item', 'total_item',
       'subtotal_cortesia_cancel', 'iva_cortesia_cancel',
       'ieps_cortesia_cancel', 'total_cortesia_cancel', 'subtotal_anulacion',
       'iva_anulacion', 'ieps_anulacion', 'total_anulacion', 'clave_platillo',
       '_source_file'],
      dtype='object')

In [3]:
df1.head()

,sucursal,operating_date,day_name,closing_time,captured_time,week_number,pdv_txn_id,order_id,order_type,order_subtype,...,subtotal_cortesia_cancel,iva_cortesia_cancel,ieps_cortesia_cancel,total_cortesia_cancel,subtotal_anulacion,iva_anulacion,ieps_anulacion,total_anulacion,clave_platillo,_source_file
0,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:48.077,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,DE005,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
1,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:52.763,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA001,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
2,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:21:04.887,2022-02-18 08:17:53.950,7,1,1,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MA003,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
3,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153,2022-02-18 08:22:25.670,7,2,2,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CBC003,detail_Panem-Carreta_2022-02-18_2022-05-07.csv
4,Panem - Carreta,2022-02-18,viernes,2022-02-18 08:24:44.153,2022-02-18 08:22:30.090,7,2,2,Para llevar,'-,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,MB005,detail_Panem-Carreta_2022-02-18_2022-05-07.csv

In [5]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [6]:
print("Número de sucursales:", df1["sucursal"].nunique())
print("Número de productos:", df1["item"].nunique())

Número de sucursales: 11
Número de productos: 666

# Paso 1 — Limpiar datos importantes

### Primero aseguramos que no haya productos vacíos y que la cantidad sea válida.

In [7]:
df_clean = df1.copy()

df_clean = df_clean.dropna(subset=["item", "quantity"])
df_clean["quantity"] = pd.to_numeric(df_clean["quantity"], errors="coerce")
df_clean = df_clean.dropna(subset=["quantity"])

# Paso 2 — Agrupar ventas por sucursal y producto

### Ahora calculamos cuánto se vende de cada producto en cada sucursal.

In [8]:
sales = (
    df_clean.groupby(["sucursal", "item"])["quantity"]
    .sum()
    .reset_index()
)

In [9]:
print("Filas en sales:", len(sales))
print("Sucursales:", sales["sucursal"].nunique())
print("Productos:", sales["item"].nunique())

Filas en sales: 2891
Sucursales: 11
Productos: 666

# Paso 3 — Obtener el Top 5 productos por sucursal

### Esto es clave para el Sankey.

In [10]:
top5_products = (
    sales.sort_values(["sucursal", "quantity"], ascending=[True, False])
    .groupby("sucursal")
    .head(5)
)

# Paso 4 — Verificar resultado

In [11]:
top5_products.head(20)

                        sucursal               item  quantity
21               Panem - Carreta        CAFE REFILL   21240.0
146              Panem - Carreta       SUBSIDIO TEC   17913.0
20               Panem - Carreta   CAFE OLLA REFILL   14530.0
47               Panem - Carreta    CONCHA VAINILLA   12513.0
84               Panem - Carreta         LATTE 16OZ    9202.0
201           Panem - Credi Club        CAFE REFILL    6523.0
225           Panem - Credi Club  CHILAQUILES PANEM    4428.0
252           Panem - Credi Club    CONCHA VAINILLA    3874.0
234           Panem - Credi Club          COCA COLA    3395.0
199           Panem - Credi Club   CAFE OLLA REFILL    2014.0
443    Panem - Hospital Zambrano        CAFE REFILL   40578.0
467    Panem - Hospital Zambrano          COCA COLA   20610.0
472    Panem - Hospital Zambrano    CONCHA VAINILLA   19220.0
427    Panem - Hospital Zambrano               AGUA   12592.0
451    Panem - Hospital Zambrano    CAPPUCCINO 16OZ   11736.0
651  Panem - Hospital Zambrano N          COCA COLA   37967.0
628  Panem - Hospital Zambrano N        CAFE REFILL   37697.0
666  Panem - Hospital Zambrano N    CONCHA VAINILLA   30961.0
645  Panem - Hospital Zambrano N  CHILAQUILES PANEM   14798.0
633  Panem - Hospital Zambrano N    CAPPUCCINO 16OZ   14270.0

In [14]:
top5_products["sucursal"].nunique()
print("Número de sucursales en top5_products:", top5_products["sucursal"].nunique())

Número de sucursales en top5_products: 11

In [15]:
top5_products["item"].nunique()
print("Número de productos únicos en top5_products:", top5_products["item"].nunique())

Número de productos únicos en top5_products: 13

# Creacion del sankey plot 
### 1. crear nodos

In [16]:
branches = top5_products["sucursal"].unique().tolist()
products = top5_products["item"].unique().tolist()

labels = branches + products

In [17]:
label_index = {label: i for i, label in enumerate(labels)}

In [18]:
source = top5_products["sucursal"].map(label_index).tolist()
target = top5_products["item"].map(label_index).tolist()
value = top5_products["quantity"].tolist()

In [19]:
import plotly.graph_objects as go

In [20]:
fig = go.Figure(data=[go.Sankey(
    node=dict(
        pad=15,
        thickness=20,
        label=labels
    ),
    link=dict(
        source=source,
        target=target,
        value=value
    )
)])

fig.update_layout(title_text="Panem Sales Flow: Branch → Top Products", font_size=12)

fig.show()